import type { Metadata } from "next";
import SessionProviderWrapper from "./SessionProviderWrapper";
import "./globals.css"; // Import your global CSS file

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="background-effect"> {/* Add className here */}
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}